pipeline {
     //agent { dockerfile { dir './Backend/TrackerAPI' } }
     agent {
    dockerfile {
        filename 'Dockerfile'
        dir './Backend/TrackerAPI'
        //label 'my-defined-label'
        registryUrl 'https://hub.docker.com/r/technasia/securecane'
        registryCredentialsId 'Dockerhub'
    }
}
    stages {
        stage('run') {
            steps {
                sh 'curl localhost:4000'
            }
        }
    }
}