pipeline {
     //agent { dockerfile { dir './Backend/TrackerAPI' } }
     agent {
    docker {
        filename 'Dockerfile'
        dir './Backend/TrackerAPI'
        //label 'my-defined-label'
        //registryUrl 'https://index.docker.io/v1/'
        //registryCredentialsId 'Dockerhub'
    }
}
     stages {
        stage('push after build') {
            steps {
               script { 
                docker.withRegistry('https://index.docker.io/v1/', 'Dockerhub') {
                    app.push("${env.BUILD_NUMBER}")
                    app.push("latest")
            }
        }
    }
}   
}
}